PointOfSale/PointOfSale/Controllers/PaymentTypeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using POS.DataAccessLayer.IServices;
using POS.DataAccessLayer.Models.Company;
using POS.DataAccessLayer.Models.Payment;

namespace PointOfSale.Controllers
{
    public class PaymentTypeController : Controller
    {
        IRepository<PaymentTypeModel> _paymentTypeRepo;

        public PaymentTypeController(IRepository<PaymentTypeModel> paymentTypeRepo)
        {
            _paymentTypeRepo = paymentTypeRepo;
        }

        public IActionResult Index() => View();

        public async Task<JsonResult> GetPaymentTypes()
        {
            return Json(new { data = await _paymentTypeRepo.GetAll() });
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Create(PaymentTypeModel model)
        {
            bool result; ModelState.Remove("PaymentId");

            if (ModelState.IsValid)
            {
                if (model.PaymentId > 0)
                {
                    result = await _paymentTypeRepo.Update(model);
                }
                else
                {
                    result = await _paymentTypeRepo.Insert(model);
                }
                return Json(new { status = result, message = result ? "Record has been submitted successfully" : "Error occured please try again" });
            }
            return Json(new { status = false, message = "Invalid input please fill the form" });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var paymentType = await _paymentTypeRepo.GetById(id);
            return View("Create", paymentType);
        }

        public async Task<JsonResult> Delete(int id)
        {
            return Json(await _paymentTypeRepo.Delete(new PaymentTypeModel { PaymentId = id }));
        }
    }
}

PointOfSale/PointOfSale/Views/PaymentType/Create.cshtml
@{ Layout = null; }

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer


@model POS.DataAccessLayer.Models.Payment.PaymentTypeModel

<form id="companyForm" asp-controller="PaymentType" asp-action="Create" class="form">
    <div class="fv-row mb-10">
        <input type="hidden" asp-for="PaymentId" />
        <label class="required form-label">@_localizer["Name"]</label>
        <input class="form-control form-control-solid mb-3 mb-lg-0" asp-for="Name" type="text">
        <span asp-validation-for="Name" class="text-danger fs-7"></span>
    </div>
    <div class="text-center">
        <button type="reset" onclick="closeModal()" class="btn btn-light me-3" data-kt-users-modal-action="cancel">@_localizer["Cancel"]</button>
        <button type="submit" class="btn btn-primary">
            <span class="indicator-label">@_localizer["Submit"]</span>
            <span class="indicator-progress">
                Please wait...
                <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
            </span>
        </button>
    </div>
</form>

<partial name="_ValidationScriptsPartial" />

PointOfSale/PointOfSale/Views/PaymentType/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer

@{
    ViewData["Title"] = _localizer["PaymentTypes"];
}

<div class="card">
    <!--begin::Card header-->
    <div class="card-header border-0 pt-6">
        <!--begin::Card title-->
        <div class="card-title">
            <!--begin::Search-->
            <div class="d-flex align-items-center position-relative my-1">
                <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                <span class="svg-icon svg-icon-1 position-absolute ms-6">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
                        <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
                    </svg>
                </span>
                <!--end::Svg Icon-->
                <input type="text" data-kt-user-table-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="@_localizer["Search"]" />
            </div>
            <!--end::Search-->
        </div>
        <!--begin::Card title-->
        <!--begin::Card toolbar-->
        <div class="card-toolbar">
            <div class="d-flex justify-content-end" data-kt-user-table-toolbar="base">
                <button type="button" class="btn btn-primary" id="add-new">
                    <span class="svg-icon svg-icon-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="11.364" y="20.364" width="16" height="2" rx="1" transform="rotate(-90 11.364 20.364)" fill="currentColor" />
                            <rect x="4.36396" y="11.364" width="16" height="2" rx="1" fill="currentColor" />
                        </svg>
                    </span>
                    @_localizer["Add"]
                </button>
            </div>
        </div>
    </div>

    <div class="card-body py-4">
        <!--begin::Table-->
        <table class="table align-middle table-row-dashed fs-6 gy-5" id="paymentTypeDataTable">
            <thead>
                <tr class="text-start text-muted fw-bolder fs-7 text-uppercase gs-0">
                    <th class="min-w-125px">@_localizer["Id"]</th>
                    <th class="min-w-125px">@_localizer["Name"]</th>
                    <th class="min-w-100px">@_localizer["Actions"]</th>
                </tr>
            </thead>
            <!--end::Table head-->
            <!--begin::Table body-->
            <tbody class="text-gray-600 fw-bold">
            </tbody>
            <!--end::Table body-->
        </table>
        <!--end::Table-->
    </div>
    <!--end::Card body-->
</div>

<partial name="_modal">
    <!--end::Modal-->

    @section scripts{
        <script src="~/js/pages/paymentType.js" asp-append-version="true"></script>
    }